version: "3.7"
services:
  bot:
    image: max-bot/ministry-of-justice:1.0
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./logs:/home/murman_konsult_bot/logs